#!/usr/bin/env python3
"""Build an auditable AIHOT source seed from the existing, selected subscriptions."""
import hashlib
import json
from pathlib import Path
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[2]
TARGET = ROOT / 'vendor/aihot/industry/sources.json'
EXTERNAL = {
    'hacker-news': 'Hacker News', 'juya': '橘鸦 AI 日报',
    'papers': 'HF 每日论文', 'trending': 'GitHub 趋势',
    'digest': 'AI Builders', 'radar': '机会雷达',
    'topics': '融合简报', 'x': 'X 关注动态（采集暂停）',
}


def build_sources(demo):
    sources = [dict(s) for s in demo if not s['id'].startswith(('ak-', 'qiaomu-', 'hub-'))]
    official = [
        {'id': 'rss-google-gemini', 'name': 'Google Gemini 官方博客', 'kind': 'rss',
         'config': {'feedUrl': 'https://blog.google/innovation-and-ai/models-and-research/gemini-models/rss/'}, 'owner_entity_id': 'google'},
        {'id': 'web-anthropic-news', 'name': 'Anthropic 官方新闻', 'kind': 'web_list', 'owner_entity_id': 'anthropic',
         'config': {'url': 'https://www.anthropic.com/news', 'parseMode': 'html',
            'itemSelector': 'main a[class*="FeaturedGrid"], main a[class*="PublicationList"][href]',
            'titleSelector': 'h2, h3, [class*="__title"], [class*="__sideTitle"]', 'publishedAtSelector': 'time',
            'publishedAtUtcOffset': '+00:00', 'allowUrlPrefixes': ['https://www.anthropic.com/news/', 'https://www.anthropic.com/claude-'],
            'detail': {'maxFetches': 8, 'titleSelector': 'h1', 'summarySelector': 'meta[name="description"]'}}},
        {'id': 'web-claude-blog', 'name': 'Claude 官方博客', 'kind': 'web_list', 'owner_entity_id': 'anthropic',
         'config': {'url': 'https://claude.com/blog', 'parseMode': 'html', 'itemSelector': '.blog_cms_item',
            'linkSelector': 'a[href^="/blog/"]', 'titleSelector': '.card_blog_title',
            'publishedAtSelector': '.card_blog_content .u-text-style-caption', 'publishedAtUtcOffset': '+00:00',
            'allowUrlPrefixes': ['https://claude.com/blog/'], 'detail': {'maxFetches': 8, 'summarySelector': 'meta[name="description"]'}}},
    ]
    for item in official:
        if not any(s['id'] == item['id'] for s in sources):
            sources.append({**item, 'tier': 'T1', 'first_party': True, 'participation_mode': 'editorial',
                'interval_minutes': 60, 'tags': ['官方'], 'site_fulltext': False, 'syndicate_fulltext': False})
    for s in sources:
        if s['id'] in {'rss-openai-news', 'rss-google-deepmind', 'rss-google-research', *(item['id'] for item in official)}:
            s['config'] = {**s['config'], 'sortByPublishedAt': True,
                '_aihot': {**s['config'].get('_aihot', {}), 'initialBackfillLimit': 8, 'publishPending': True}}
    seen = {s.get('config', {}).get('feedUrl') for s in sources}

    def add(name, url, origin):
        if not url or url in seen:
            return
        seen.add(url)
        sources.append({'id': f'{origin}-' + hashlib.sha256(url.encode()).hexdigest()[:12],
            'name': name, 'kind': 'rss', 'config': {'feedUrl': url, '_aihot': {'initialBackfillLimit': 2}},
            'tier': 'T2', 'first_party': False, 'participation_mode': 'editorial',
            'interval_minutes': 120, 'tags': [origin, '个人订阅'],
            'site_fulltext': False, 'syndicate_fulltext': False})

    for node in ET.parse(ROOT / 'skills/ak-rss-digest/references/feeds.opml').findall('.//outline[@xmlUrl]'):
        add(node.get('title') or node.get('text'), node.get('xmlUrl'), 'ak')
    ai = [f for f in json.loads((ROOT / 'data/qiaomu-rss/tidings.json').read_text())['feeds'] if 'ai' in f.get('packs', [])]
    for feed in ai[:3]:  # Matches the existing collector selection, not the entire catalogue.
        add(feed['title'], feed['feed_url'], 'qiaomu')
    for key, name in EXTERNAL.items():
        sources.append({'id': 'hub-' + key, 'name': name, 'kind': 'external', 'config': {},
            'tier': 'T2', 'participation_mode': 'editorial', 'interval_minutes': 120,
            'enabled': key != 'x', 'tags': ['旧站适配', key],
            'site_fulltext': False, 'syndicate_fulltext': False})
    # Read-only history endpoints for aggregate RSS snapshots, never collected twice.
    for key, name in [('rss', '乔木 RSS（迁移存量）'), ('ak-rss', 'AK RSS（迁移存量）')]:
        sources.append({'id': 'hub-' + key, 'name': name, 'kind': 'external', 'config': {},
            'tier': 'T2', 'participation_mode': 'editorial', 'enabled': False,
            'site_fulltext': False, 'syndicate_fulltext': False})
    return {'$comment': 'Upstream examples + existing subscriptions; generated by tools/aihot/subscriptions.py. X paused.', 'sources': sources}


if __name__ == '__main__':
    value = build_sources(json.loads(TARGET.read_text())['sources'])
    TARGET.write_text(json.dumps(value, ensure_ascii=False, indent=2) + '\n')
    print(json.dumps({'sources': len(value['sources']), 'rss': sum(s['kind'] == 'rss' for s in value['sources']), 'paused': sum(s.get('enabled') is False for s in value['sources'])}))
