#!/usr/bin/env python3
"""Build an auditable AIHOT source seed from the existing, selected subscriptions."""
import hashlib
import json
from pathlib import Path
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[2]
TARGET = ROOT / 'vendor/aihot/industry/sources.json'
EXTERNAL = {
    'hacker-news': 'Hacker News', 'juya': '橘鸦 AI 日报',
    'papers': 'HF 每日论文', 'trending': 'GitHub 趋势',
    'digest': 'AI Builders', 'radar': '机会雷达',
    'topics': '融合简报', 'x': 'X 关注动态（采集暂停）',
}


def build_sources(demo):
    sources = [dict(s) for s in demo if not s['id'].startswith(('ak-', 'qiaomu-', 'hub-'))]
    seen = {s.get('config', {}).get('feedUrl') for s in sources}

    def add(name, url, origin):
        if not url or url in seen:
            return
        seen.add(url)
        sources.append({'id': f'{origin}-' + hashlib.sha256(url.encode()).hexdigest()[:12],
            'name': name, 'kind': 'rss', 'config': {'feedUrl': url, '_aihot': {'initialBackfillLimit': 2}},
            'tier': 'T2', 'first_party': False, 'participation_mode': 'editorial',
            'interval_minutes': 120, 'tags': [origin, '个人订阅'],
            'site_fulltext': False, 'syndicate_fulltext': False})

    for node in ET.parse(ROOT / 'skills/ak-rss-digest/references/feeds.opml').findall('.//outline[@xmlUrl]'):
        add(node.get('title') or node.get('text'), node.get('xmlUrl'), 'ak')
    ai = [f for f in json.loads((ROOT / 'data/qiaomu-rss/tidings.json').read_text())['feeds'] if 'ai' in f.get('packs', [])]
    for feed in ai[:3]:  # Matches the existing collector selection, not the entire catalogue.
        add(feed['title'], feed['feed_url'], 'qiaomu')
    for key, name in EXTERNAL.items():
        sources.append({'id': 'hub-' + key, 'name': name, 'kind': 'external', 'config': {},
            'tier': 'T2', 'participation_mode': 'editorial', 'interval_minutes': 120,
            'enabled': key != 'x', 'tags': ['旧站适配', key],
            'site_fulltext': False, 'syndicate_fulltext': False})
    # Read-only history endpoints for aggregate RSS snapshots, never collected twice.
    for key, name in [('rss', '乔木 RSS（迁移存量）'), ('ak-rss', 'AK RSS（迁移存量）')]:
        sources.append({'id': 'hub-' + key, 'name': name, 'kind': 'external', 'config': {},
            'tier': 'T2', 'participation_mode': 'editorial', 'enabled': False,
            'site_fulltext': False, 'syndicate_fulltext': False})
    return {'$comment': 'Upstream examples + existing subscriptions; generated by tools/aihot/subscriptions.py. X paused.', 'sources': sources}


if __name__ == '__main__':
    value = build_sources(json.loads(TARGET.read_text())['sources'])
    TARGET.write_text(json.dumps(value, ensure_ascii=False, indent=2) + '\n')
    print(json.dumps({'sources': len(value['sources']), 'rss': sum(s['kind'] == 'rss' for s in value['sources']), 'paused': sum(s.get('enabled') is False for s in value['sources'])}))
